### ISSUE TITLE
SV-86863r2_rule, Fix Method: "RhostsRSAAuthentication yes"

### ISSUE THREAD

**Issue by kjellgren** [hardenedlinux/STIG-4-Debian#12]
Setting value to "no" should fix the failing rule (?)

**Comment by Samson-W** [comment]
The original implementation is described in the documentation U_Red_Hat_Enterprise_Linux_7_STIG_V1R1_Manual-xccdf.xml (from http://iasecontent.disa.mil/stigs/zip/U_Red_Hat_Enterprise_Linux_7_V1R1_STIG.ZIP), the description in this document is incorrect.
