### ISSUE TITLE
Suggestion: Consider using Ubuntu STIG for base

### ISSUE THREAD

**Issue by WSLUser** [hardenedlinux/STIG-4-Debian#15]
Considering that Ubuntu and Debian are very similar, I would expect the porting process to go much faster and easier than porting from RHEL, which is RPM based.

**Comment by citypw** [comment]
Thanks for the advice. But not sure how long we're gonna maintain this project. Plz see our current active project is harbian-audit which integrated some STIG policies:

https://github.com/hardenedlinux/harbian-audit

**Comment by Samson-W** [comment]
It has been noted that the Ubuntu-based STIG standard (https://iasecontent.disa.mil/stigs/zip/U_Canonical_Ubuntu_16-04_LTS_V1R1_STIG.zip) will be considered for development based on this version in future updates.

Thanks for  your suggestion.
