### ISSUE TITLE
SV-86535r1 has reverse logic

### ISSUE THREAD

**Issue by gwijnja** [hardenedlinux/STIG-4-Debian#19]
The "difok" option in `/etc/pam.d/common-password` sets the number of characters in a password that must not be present in the old password. If the value of "difok" is set to less than "8", this is a finding.

But the script checks for "greater or equal to" 8:

```bash
bash scripts/check-password.sh /etc/pam.d/common-password pam_pwquality.so difok ge 8 >/dev/null 2>&1 &
```

should be

```bash
bash scripts/check-password.sh /etc/pam.d/common-password pam_pwquality.so difok lt 8 >/dev/null 2>&1 &
```

**Comment by gwijnja** [comment]
And this one also has reverse logic:

```bash
bash scripts/check-password.sh /etc/pam.d/common-password pam_pwquality.so minclass ge 4 >/dev/null 2>&1 &
```

The documentation says: _If the value of "minclass" is set to less than "4", this is a finding._ And this is correct, so the check is wrong.

"ge 4" should be "lt 4"

**Comment by Samson-W** [comment]
> And this one also has reverse logic:
> 
> ```shell
> bash scripts/check-password.sh /etc/pam.d/common-password pam_pwquality.so minclass ge 4 >/dev/null 2>&1 &
> ```
> 
> The documentation says: _If the value of "minclass" is set to less than "4", this is a finding._ And this is correct, so the check is wrong.
> 
> "ge 4" should be "lt 4"

Yes, there are two bugs, thanks for reporting!

**Comment by Samson-W** [comment]
Fix two bugs
