### ISSUE TITLE
check.sh: 10: check.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by MetaAbstract** [hardenedlinux/STIG-4-Debian#4]
melchukaa@ws:~/Data/soft_no_install/STIG-4-Debian-master$ sh check.sh 
check.sh: 10: check.sh: Syntax error: "(" unexpected

**Comment by citypw** [comment]
Could you plz replace "dash/sh" with "bash"?

**Comment by MetaAbstract** [comment]
Sorry. With bash it's run ok, but no log. "sudo bush check.sh" - right way?

**Comment by MetaAbstract** [comment]
Under the root no log in /var/log again.

**Comment by citypw** [comment]
Can you try this again?

#sudo ./check.sh -s

**Comment by MetaAbstract** [comment]
Work fine. thx!!!

**Comment by citypw** [comment]
Happy auditing!
